---
cog_bundle_version: 4
name: groove
description: Groove helpdesk commands
version: 0.2.0
docker:
  image: cogcmd/groove
  tag: 0.2.1
permissions:
- groove:agent
commands:
  trigger:
    executable: "/home/bundle/cog-command"
    description: Accept inbound ticket creation webhook events from GrooveHQ
    documentation: |
      groove:trigger - Accept inbound ticket creation webhook events from GrooveHQ

      Accepts a webhook payload for a ticket creation event from GrooveHQ and
      applies a simple template to it. Should be used as the first stage of a
      pipeline in a Trigger. For example, the following pipeline would receive
      a ticket event and announce the ticket to your #support channel.

      Example:
        groove:trigger > chat://#support
    rules:
    - allow
  ticket:
    executable: "/home/bundle/cog-command"
    description: Return details for an individual Groove ticket
    documentation: |
      groove:ticket <number> - Show a specific Groove ticket

      Returns the details of a specific ticket and the 5 most recent messages
      within the ticket.
    rules:
    - when command is groove:ticket must have groove:agent
  tickets:
    executable: "/home/bundle/cog-command"
    description: Return a list of Groove tickets
    documentation: |
      groove:tickets - List Groove tickets

      Lists tickets in a GrooveHQ account. If called with no options, it
      will return all tickets that are in the unread or opened states.

      Options:
        [--state|-s <state>] - Filter ticket list by state
        [--assignee|-a <email>] - Filter ticket list by assignee
        [--from|-f <email>] - Filter ticket list by ticket creator
    options:
      state:
        description: 'only list tickets with this state (possible values: unread,
          opened, pending, closed, spam)'
        type: string
        required: false
        short_flag: s
      assignee:
        description: only list tickets assigned to this user (email address)
        type: string
        required: false
        short_flag: a
      from:
        description: only list tickets from this customer (email address)
        type: string
        required: false
        short_flag: f
    rules:
    - when command is groove:tickets must have groove:agent
templates:
  table:
    body: |
      ~each var=$results as=result~
      ```~$result.table~```
      ~end~
  ticket:
    body: |
      ~each var=$results as=result~
      *From:* ~$result.ticket.customer_name~
      *Subject:* ~$result.ticket.title~
      *Date:* ~$result.ticket.created_at~

      ~if cond=$result.messages not_empty?~
      ~each var=$result.messages as=message~
      _*~$message.from~*_
      ~$message.body~
      ~end~
      ~end~
  trigger:
    body: |
      ~each var=$results as=result~
      *New Ticket:* ~$result.ticket.mailbox~

      *From:* ~$result.ticket.customer_name~
      *Subject:* ~$result.ticket.title~
      *Date:* ~$result.ticket.created_at~

      ~$result.ticket.last_message_plain_text~
      ~end~
